#pragma once
//k
void middle_goal_1();
void low_goal_1();
void test();
void base_7();
void left_long_goal_7();
void right_long_goal_7();
void base_9();
void left_long_goal_9();  
void right_long_goal_9(); 
void solo_awp();
void skills();
void default_constants();
void drive_example();
void turn_example();
void drive_and_turn();
void wait_until_change_speed();
void swing_example();
void motion_chaining();
void combining_movements();
void interfered_example();
void odom_drive_example();
void odom_pure_pursuit_example();
void odom_pure_pursuit_wait_until_example();
void odom_boomerang_example();
void odom_boomerang_injected_pure_pursuit_example();
void measure_offsets();